pub mod claude_install;
pub mod codex_install;
pub mod credentials;
pub mod embedding_index;
pub mod filesystem;
pub mod gemini_install;
pub mod git;
pub mod host_install;
#[cfg(feature = "local-embed")]
pub mod local_embedding;
pub mod metrics;
pub mod openai_compatible;
pub mod opencode_install;
pub mod pre_tool_use;
pub mod repo_install;
pub mod ripgrep;
#[cfg(feature = "ast")]
pub mod tree_sitter_chunker;
